name: Publish Python Package with Trusted Publishing

on:
   push:
     branches:
        - main

jobs:
  publish-to-pypi:
    name: Build and Publish to PyPI via Trusted Publishing
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT for trusted publishing
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the package
      run: |
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
